parameters:
    ehann_frontend.twig.extension.class: Ehann\FrontendBundle\Twig\EhannFrontendTwigExtension

services:
    ehann_frontend.twig.extension:
        class: %ehann_frontend.twig.extension.class%
        arguments: [ @service_container ]
        tags:
          - { name: twig.extension }